Add the context parameter to the mfd configuration hooks
ESSS/alfasim-sdk pull request #129
Opened 2020-12-10 15:39 UTC by williamjamir

ASIM-4008

2020-12-10 15:46 UTC, nicoddemus requested changes

2020-12-10 15:46 UTC, nicoddemus commented on HISTORY.rst
> +* Add support for context on alfasim_configure_fields, alfasim_configure_layers and alfasim_configure_phases
```suggestion
* Add context support on ``alfasim_configure_fields``, ``alfasim_configure_layers`` and ``alfasim_configure_phases``.
```

2020-12-10 15:46 UTC, nicoddemus commented on src/_alfasim_sdk/version.py
> +__version__ = "0.7.1"
```suggestion
__version__ = "0.8.0"
```

Being able to receive a context is definitely a new feature. 👍

2020-12-11 12:11 UTC, nicoddemus approved these changes

2020-12-11 17:14 UTC, oliveira-mauricio commented on src/_alfasim_sdk/hook_specs_gui.py
> +     The ``ctx`` parameter is provided to retrieve information about the current state of the application and the current value
There is an extra space 🤷🏼‍♂️

2020-12-11 17:15 UTC, oliveira-mauricio approved these changes
The plugins should be updated too.

2020-12-17 20:15 UTC, prusse-martin approved these changes

2021-01-05 12:23 UTC, merged