Update release date in `HISTORY.rst`
ESSS/alfasim-sdk pull request #178
Opened 2021-06-29 20:32 UTC by prusse-martin

2021-06-30 11:42 UTC, nicoddemus approved these changes

2021-06-30 14:26 UTC, oliveira-mauricio approved these changes

2021-07-01 17:37 UTC, oliveira-mauricio approved these changes

2021-07-01 17:51 UTC, nicoddemus requested changes

2021-07-01 17:51 UTC, nicoddemus commented on requirements_dev.txt
>  typing_inspect
```suggestion
```

2021-07-01 17:51 UTC, nicoddemus commented on requirements_dev.txt
> +barril>=1.10,<1.11
```suggestion
```

2021-07-01 17:51 UTC, nicoddemus commented on setup.cfg
>      barril>=1.9.0
```suggestion
    barril>=1.10,<1.11
```

2021-07-01 17:51 UTC, nicoddemus commented on setup.cfg
> +    strictyaml==1.3.2
```suggestion
    strictyaml<1.4
```

2021-07-01 17:51 UTC, nicoddemus commented on setup.cfg
> +    ruamel.yaml==0.16.12
```suggestion
```

2021-07-01 17:51 UTC, nicoddemus commented on HISTORY.rst
> +* Temporary pin strictyaml (dependency) due conflicts.
```suggestion
* Temporarily pin ``strictyaml`` dependency due to conflicts.
```

2021-07-01 17:51 UTC, nicoddemus commented on setup.cfg
> +# TODO: #180 Temporary pin strictyaml (with ruamel.yaml).
```suggestion
```

2021-07-01 21:02 UTC, prusse-martin commented on setup.cfg
> +    ruamel.yaml<0.16.13
I did return the ruamel pin, `0.16.13` was causing failures (aparentlly interface changes).
Note that strictyaml in `1.4.3` in now bundling ruamel `0.16.12`.

2021-07-02 11:21 UTC, nicoddemus approved these changes

2021-07-02 12:58 UTC, merged