(ASIM-4457) rename discharge coeff attributes
ESSS/alfasim-sdk pull request #211
Opened 2021-11-29 12:50 UTC by dettmerramon

2021-11-30 20:01 UTC, oliveira-mauricio approved these changes

2021-12-01 16:57 UTC, nicoddemus approved these changes

2021-12-06 17:20 UTC, prusse-martin requested changes
This a breaking change.
We will not be able to load old alfacases containing a gas lift valve.

This is missing a changelog entry.
We really want to add that breaking change?

2021-12-06 17:24 UTC, nicoddemus commented
> We really want to add that breaking change?

I would like, for consistency. Better now than never I think.

Don't we have a mechanism to allow loading attributes with different names? Can we estimate if there are many alfacase files out there which use gas lift valves?

Unless I'm mistaken users of alfascase files are ourselves and PWDa, so I suspect the change is OK to apply now.

2021-12-06 17:26 UTC, prusse-martin approved these changes

2021-12-06 17:28 UTC, prusse-martin commented
> Don't we have a mechanism to allow loading attributes with different names?

No, we don't.

> Unless I'm mistaken users of alfascase files are ourselves and PWDa, so I suspect the change is OK to apply now.

OK...

2021-12-08 16:32 UTC, merged