Merge ALFAsim RB-v23.1.0 features into master
ESSS/alfasim-sdk pull request #308
Opened 2023-05-12 13:36 UTC by Gualcar

2023-05-12 18:52 UTC, Gualcar commented
I will attack the fix of `to_curve` (ASIM-5237) method in a different PR to not mix things.

2023-05-16 14:19 UTC, prusse-martin requested changes

2023-05-16 14:19 UTC, prusse-martin commented on CHANGELOG.rst
> -* Disable internal hdf file locks.
This should not be removed.

2023-05-16 14:49 UTC, Gualcar commented on CHANGELOG.rst
> -* Disable internal hdf file locks.
Fixed!

2023-05-17 15:06 UTC, merged