Add proper support for Controller equipment
ESSS/alfasim-sdk pull request #381
Opened 2024-05-10 16:25 UTC by cauebs

2024-05-14 14:40 UTC, nicoddemus requested changes
LGTM, just missing the CHANGELOG entry.

2024-05-14 21:11 UTC, prusse-martin approved these changes

2024-05-14 21:11 UTC, prusse-martin commented on tests/common_testing/alfasim_sdk_common_testing/filled_case_descriptions.py
>  )
Just a comment.

"Carbon Steel" formation =P
Are we drilling some weird mineral deposit?

2024-05-15 20:01 UTC, ro-oliveira95 approved these changes

2024-05-16 11:37 UTC, nicoddemus approved these changes

2024-05-16 12:41 UTC, merged